### ISSUE TITLE
Why my swiper slide from the last slide?

### ISSUE THREAD

**Issue by Manjiz** [surmon-china/vue-awesome-swiper#106]
Without setting the `initialSlide`, my swiper always slide from the last slide. As I set it to 1, it works (Slide from the first slide). Why not Zero.

``` js
swiperOption: {
    pagination: '.swiper-pagination',
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    slidesPerView: 1,
    paginationClickable: true,
    spaceBetween: 30,
    loop: true,
    autoplay: 3000,
    autoplayDisableOnInteraction: false
}
```

**Comment by surmon-china** [comment]
I have a local test, did not find this problem, can you provide a more detailed description of it?

![image](https://user-images.githubusercontent.com/14019524/27293886-50683bc4-554a-11e7-951e-65c67752f1c9.png)

**Comment by Manjiz** [comment]
@surmon-china It arose when I used the loop (`v-for`).

``` js
  <swiper :options="swiperOption" ref="test" class="category_carousel">
    <swiper-slide
      v-for="(item, index) in classAdsActivity"
      :key="item.id"
      class="J_ping">
      <a :href="item.url">
        <img :src="item.image">
      </a>
    </swiper-slide>
    <div class="swiper-pagination" slot="pagination"></div>
  </swiper>
```

**Comment by surmon-china** [comment]
Me too.

![image](https://user-images.githubusercontent.com/14019524/27313690-ca5160ee-55a1-11e7-9a38-e2908984e7a8.png)

**Comment by surmon-china** [comment]
Check if your array order is within your expectations?

**Comment by Manjiz** [comment]
Map with the name of Array Item: ['贝恩斯xxx', '欢乐谷xxx', '优惠xxx', '总攻略xxx']

**Comment by Manjiz** [comment]
It works when setting `loop: false`.
The `swiper.activeIndex` in `onTransitionEnd` shows the strange order [5, 2, 3, 4]. I think there's something wrong with loop.

**Comment by Manjiz** [comment]
@surmon-china 

> Note: As the array is in `data`, there is no problem.

`mapGetters({classAdsActivity: 'classAdsActivity'})`. The initial state of `classAdsActivity` is `[]`.

**Comment by simone-sanfratello** [comment]
had same problem, fixed with
````js
swiperOption: {
        ...
        onInit: function (swiper) {
          swiper.slideTo(1)
        }
````

@surmon-china thanks for this great plugin

**Comment by hgawait** [comment]
My solution is：
swiperOption: {
        ...
        initialSlide: 1
}

**Comment by imsidz** [comment]
did anyone fixed it because i am still getting same problem

**Comment by azerroth11** [comment]
Nope, still getting the issue in 2023. Even though there have been a myriad of threads opened, none have been fixed and all have been closed by the author. He states that in v9 it has completely been redone but there is no difference and the issue is still there.
