### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by mateomrqz** [surmon-china/vue-awesome-swiper#9]
Hi! I'm trying to implement your Slider, but I'm having some issues:

     SyntaxError: Unexpected token (2:0) while parsing ~/node_modules/vue-awesome-swiper/swiper.vue while parsing file:
     ~/node_modules/vue-awesome-swiper/swiper.vue

     ~/node_modules/vue-awesome-swiper/slide.vue:1
     <template>
     ^

Any reason why this is happening? I used the **npm install method** Thanks!

*Apologize for the basic question ^_^

**Comment by jbrialon** [comment]
same, i'm using browserify

**Comment by surmon-china** [comment]
use [vue-cli](https://github.com/vuejs/vue-cli) init your vue peoject

**Comment by jbrialon** [comment]
that wasn't helpfull at all,

@mateomrqz I fixed it myself by requiring the components the old fashion way : 

`components: {
                'swiper': require('../../components/swiper/swiper.vue'),
                'swiper-slide': require('../../components/swiper/slide.vue')
            }`

some more adjustement were needed, let me know if you want more help

**Comment by mateomrqz** [comment]
@jbrialon Thank you so much! I temporarily fixed my issues by including the swiper.vue and slide.vue directly in my projects, not ideal, but allowed me to kept working. I will implement your suggestion today!

@surmon-china I used vue cli + browserify template and still the issue persists! This is an excellent slider for Vue, thank you so much!

**Comment by surmon-china** [comment]
Sorry, it may temporarily not support browserify

**Comment by weexpectedTHIS** [comment]
So this is still the case, you still don't support browserify? I'm still getting the same parsing error.
